language: python
python:
  - "2.7"
addons:
  apt:
    packages:
      - doxygen
install:
  - pip install .
  - pip install -r test_required_packages.req
  - pip install -r build_required_packages.req
script:
  - ./build.sh
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: $TRAVIS_BUILD_DIR/docs/html
  github_token: $GH_REPO_TOKEN
  on:
    branch: master
