"""@ingroup default_suites
@file
Contains the quality suite definitions necessary for doxygen enforcement.
"""
from vigilence.configuration import ConfigurationStanza
from vigilence.constraint import Constraint
from vigilence.parser import Parser
from vigilence.representation import QualityItem, QualityReport, Satisfaction
from vigilence.suite import QualitySuite

class DocumentationError(QualityItem):
    """Represents a single documentation error from a Doxygen run.
    """
    def __init__(self, error): #pylint: disable=useless-super-delegation
        super(DocumentationError, self).__init__(error)

    @property
    def identifier(self):
        return self.metrics

class DoxygenParser(Parser):
    """A Parser implementation for Doxygen error reports.
    These reports should be generated by redirecting stderr from the doxygen command to a file.
    """
    def parse(self, fileContents):
        docErrors = [DocumentationError(line) for line in fileContents.split('\n') if line]
        return QualityReport(docErrors)

class Documentation(Constraint):
    """A Constraint that enforces documentation.
    """
    def satisfied_by(self, item):
        return Satisfaction(False, item.identifier)

class DocumentationStanza(ConfigurationStanza):
    """The documentation configuration stanza.
    """
    def parse(self, stanza):
        return [Documentation()]

QualitySuite.add_suite('doxygen',
                       DoxygenParser(),
                       {'documentation': Documentation},
                       {'documentation': DocumentationStanza})
